# 개발 환경 설정
server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET SESSION hibernate.jdbc.lob.non_contextual_creation=true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.sprint.mission.discodeit: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.orm.jdbc.bind: trace


info:
  # 데이터소스 정보
  datasource:
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}

  # JPA 설정 정보
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto}

  # 스토리지 설정 정보
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}

    # 멀티파트 설정 정보
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}